# 각 세션별 DEV/PROD 경로를 정의하세요.

[session_9]
  [session_9.DEV]

  TEMPLATE_PATH = "/content/drive/MyDrive/Colab Notebooks/52.KHCU_MR24/MR_09_파이썬 기초_학번_성명.ipynb"
  ANSWER_PATH = "/content/drive/MyDrive/Colab Notebooks/52.KHCU_MR24/MR_09_파이썬 기초_학번_성명_src.ipynb"
  SUBMIT_DIR    = "/content/drive/MyDrive/Colab Notebooks/2024 마케팅조사론/9차시"
  OUT_DIR       = "/content/drive/MyDrive/Colab Notebooks/2024 마케팅조사론/Autograde/9차시"

  [session_9.PROD]
  TEMPLATE_PATH = "/content/drive/MyDrive/Colab Notebooks/52.KHCU_MR25/MR_09_파이썬 기초_학번_성명.ipynb"
  ANSWER_PATH = "/content/drive/MyDrive/Colab Notebooks/52.KHCU_MR25/MR_09_파이썬 기초_학번_성명_src.ipynb"
  SUBMIT_DIR    = "/content/drive/MyDrive/Colab Notebooks/52.KHCU_MR25/9차시"
  OUT_DIR       = "/content/drive/MyDrive/Colab Notebooks/52.KHCU_MR25/Autograde/9차시"

[session_10]
  [session_10.DEV]
  TEMPLATE_PATH = "/content/drive/MyDrive/Colab Notebooks/52.KHCU_MR24/MR_10_기술통계분석_학번_성명.ipynb"
  ANSWER_PATH = "/content/drive/MyDrive/Colab Notebooks/52.KHCU_MR24/MR_10_기술통계분석_학번_성명_src_v2024.ipynb"
  SUBMIT_DIR    = "/content/drive/MyDrive/Colab Notebooks/2024 마케팅조사론/10차시"
  OUT_DIR       = "/content/drive/MyDrive/Colab Notebooks/2024 마케팅조사론/Autograde/10차시"


  [session_10.PROD]
  TEMPLATE_PATH = "/content/drive/MyDrive/Colab Notebooks/52.KHCU_MR25/MR_10_기술통계분석_학번_성명.ipynb"
  ANSWER_PATH = "/content/drive/MyDrive/Colab Notebooks/52.KHCU_MR25/MR_10_기술통계분석_학번_성명_src_v2025.ipynb"
  SUBMIT_DIR    = "/content/drive/MyDrive/Colab Notebooks/52.KHCU_MR25/10차시"
  OUT_DIR       = "/content/drive/MyDrive/Colab Notebooks/52.KHCU_MR25/Autograde/10차시"

[session_11]
  [session_11.DEV]
  TEMPLATE_PATH = "/content/drive/MyDrive/Colab Notebooks/52.KHCU_MR24/MR_11_상관분석_학번_성명.ipynb"
  ANSWER_PATH = "/content/drive/MyDrive/Colab Notebooks/52.KHCU_MR24/MR_11_상관분석_학번_성명_src_v2024.ipynb"
  SUBMIT_DIR    = "/content/drive/MyDrive/Colab Notebooks/2024 마케팅조사론/11차시"
  OUT_DIR       = "/content/drive/MyDrive/Colab Notebooks/2024 마케팅조사론/Autograde/11차시"


  [session_11.PROD]
  TEMPLATE_PATH = "/content/drive/MyDrive/Colab Notebooks/52.KHCU_MR25/MR_11_상관분석_학번_성명.ipynb"
  ANSWER_PATH = "/content/drive/MyDrive/Colab Notebooks/52.KHCU_MR25/MR_11_상관분석_학번_성명_src_v2025.ipynb"
  SUBMIT_DIR    = "/content/drive/MyDrive/Colab Notebooks/52.KHCU_MR25/11차시"
  OUT_DIR       = "/content/drive/MyDrive/Colab Notebooks/52.KHCU_MR25/Autograde/11차시"

  [session_12]
  [session_12.DEV]
  TEMPLATE_PATH = "/content/drive/MyDrive/Colab Notebooks/52.KHCU_MR24/MR_12_회귀분석_학번_성명.ipynb"
  ANSWER_PATH = "/content/drive/MyDrive/Colab Notebooks/52.KHCU_MR24/MR_12_회귀분석_학번_성명_src_v2024.ipynb"
  SUBMIT_DIR    = "/content/drive/MyDrive/Colab Notebooks/2024 마케팅조사론/12차시"
  OUT_DIR       = "/content/drive/MyDrive/Colab Notebooks/2024 마케팅조사론/Autograde/12차시"


  [session_12.PROD]
  TEMPLATE_PATH = "/content/drive/MyDrive/Colab Notebooks/52.KHCU_MR25/MR_12_회귀분석_학번_성명.ipynb"
  ANSWER_PATH = "/content/drive/MyDrive/Colab Notebooks/52.KHCU_MR25/MR_12_회귀분석_학번_성명_src_v2025.ipynb"
  SUBMIT_DIR    = "/content/drive/MyDrive/Colab Notebooks/52.KHCU_MR25/12차시"
  OUT_DIR       = "/content/drive/MyDrive/Colab Notebooks/52.KHCU_MR25/Autograde/12차시"

